[package]
name = "summerequinox/datacache"
description = "DataCache is a strictly-typed, privacy-driven, lightweight cache of data for the LocalPlayer."
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"